"""Composed interactive HTML report.

Takes a Manifest (or its JSON path) and produces a self-contained HTML
file with embedded Plotly figures + the analysis summary table.

The report is one Plotly chart for each implemented analysis, stacked
vertically with Jinja-rendered headings + interpretation text.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..analyze.distribution import DistributionResult, distribution
from ..errors import IOError as OntIOError
from ..io.manifest import Manifest


@dataclass
class HtmlReport:
    """Result of `build_html_report()`."""

    output_path: str
    sections: list[str]
    n_reads: int


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ont-end-reason report — {root}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            max-width: 1100px; margin: 2em auto; padding: 0 1em;
            color: #1a1a1a; background: #fafafa; }}
    h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
    h2 {{ margin-top: 2em; color: #333; }}
    .status-OK {{ color: #2ca02c; font-weight: bold; }}
    .status-CHECK {{ color: #ff7f0e; font-weight: bold; }}
    .status-FAIL {{ color: #d62728; font-weight: bold; }}
    table {{ border-collapse: collapse; margin: 1em 0; }}
    th, td {{ border: 1px solid #ddd; padding: 0.4em 0.8em; }}
    th {{ background: #eee; text-align: left; }}
    .meta {{ color: #666; font-size: 0.9em; }}
    .interp {{ background: #f0f4f8; padding: 1em; border-left: 4px solid #4a7298;
               margin: 1em 0; }}
  </style>
</head>
<body>
  <h1>ont-end-reason report</h1>
  <p class="meta"><strong>Source:</strong> {root}<br>
     <strong>Generated:</strong> {generated_at}<br>
     <strong>Tool version:</strong> {tool_version}</p>

  <h2>End reason distribution</h2>
  <p>Quality status: <span class="status-{status}">{status}</span> &middot;
     Total reads: {n_reads:,}</p>
  <div class="interp">{interpretation}</div>
  {distribution_chart}

  <table>
    <tr><th>End reason</th><th>Count</th><th>%</th></tr>
    {rows}
  </table>

  <h2>Footer</h2>
  <p class="meta">Generated by
     <a href="https://github.com/Single-Molecule-Sequencing/ont-end-reason">
     ont-end-reason</a> {tool_version}. Companion to the end-reason paper.</p>
</body>
</html>
"""


def _render_distribution_chart_html(result: DistributionResult) -> str:
    """Render the distribution chart as a Plotly HTML snippet, falling back to
    a plain text summary if Plotly isn't installed."""
    try:
        from .. import viz

        fig = viz.interactive.interactive_distribution(result)  # type: ignore[attr-defined]
        return fig.to_html(include_plotlyjs="cdn", full_html=False)
    except OntIOError:
        # Plotly not installed; fall back to text
        rows = "\n".join(
            f"  {k:35s} {v:>8,d}  {result.percentages[k] * 100:6.2f}%"
            for k, v in result.counts.items()
        )
        return f"<pre>{rows}</pre>"


def build_html_report(
    source: str | Path | Manifest,
    *,
    output_path: str | Path,
    quick: bool = False,
) -> HtmlReport:
    """Build a self-contained HTML report from a Manifest or path.

    The report currently has one section (distribution). As v0.2.0 fills in
    the other analyses, sections will be appended.
    """
    from .. import __version__

    if isinstance(source, Manifest):
        manifest = source
        # Use the first summary in the manifest for the analysis
        if not manifest.summaries:
            raise OntIOError("Manifest has no sequencing_summary files")
        analysis_source = manifest.summaries[0].path
        root_str = manifest.root
    else:
        path = Path(source)
        if path.is_file() and path.suffix == ".json":
            manifest = Manifest.from_json(path)
            analysis_source = (
                manifest.summaries[0].path
                if manifest.summaries
                else (manifest.pod5[0].path if manifest.pod5 else None)
            )
            if analysis_source is None:
                raise OntIOError("Manifest has no analyzable inputs")
            root_str = manifest.root
        else:
            analysis_source = str(path)
            root_str = str(path)

    result = distribution(analysis_source, quick=quick)
    chart_html = _render_distribution_chart_html(result)
    rows_html = "\n".join(
        f"    <tr><td>{k}</td><td>{v:,}</td><td>{result.percentages[k] * 100:.2f}%</td></tr>"
        for k, v in result.counts.items()
    )

    from datetime import datetime, timezone

    html = _HTML_TEMPLATE.format(
        root=root_str,
        generated_at=datetime.now(tz=timezone.utc).isoformat(),
        tool_version=__version__,
        status=result.quality_status,
        n_reads=result.total_reads,
        interpretation=result.interpretation,
        distribution_chart=chart_html,
        rows=rows_html,
    )

    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html)

    return HtmlReport(
        output_path=str(out_path),
        sections=["distribution"],
        n_reads=result.total_reads,
    )
